name: Deploy Frontend to S3

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug PWD & list
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la
        working-directory: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # devDependencies も含めてインストール（NODE_ENVは未指定=デフォでdevDepsも入る）
      - name: Install deps
        run: npm ci
        working-directory: .

      - name: Check Next installed
        run: npx --no-install next --version
        working-directory: .

      # === ここから API Gateway URL の受け渡しを NEXT_PUBLIC_API_GATEWAY に揃える ===
      - name: Guard - API gateway URL is set
        env:
          NEXT_PUBLIC_API_GATEWAY: ${{ secrets.NEXT_PUBLIC_API_GATEWAY }}
        run: |
          test -n "$NEXT_PUBLIC_API_GATEWAY" || (echo "ERROR: NEXT_PUBLIC_API_GATEWAY is empty"; exit 1)
        working-directory: .

      - name: Create .env.production
        run: |
          cat > .env.production << 'EOF'
          NEXT_PUBLIC_API_GATEWAY=${{ secrets.NEXT_PUBLIC_API_GATEWAY }}
          API_GATEWAY=${{ secrets.NEXT_PUBLIC_API_GATEWAY }}
          NEXT_PUBLIC_COGNITO_DOMAIN=${{ secrets.NEXT_PUBLIC_COGNITO_DOMAIN }}
          NEXT_PUBLIC_COGNITO_CLIENT_ID=${{ secrets.NEXT_PUBLIC_COGNITO_CLIENT_ID }}
          NEXT_PUBLIC_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
          EOF
        working-directory: .

      - name: Build (Next.js static export)
        env:
          NEXT_PUBLIC_API_GATEWAY: ${{ secrets.NEXT_PUBLIC_API_GATEWAY }}
        run: |
          npm run build
          test -d out || (echo "out/ not found after export"; exit 1)
        working-directory: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-northeast-1' }}

      - name: Sync to S3
        run: aws s3 sync out s3://${{ secrets.FRONTEND_S3_BUCKET }} --delete
        working-directory: .

      - name: Guard - CloudFront distribution ID is set
        env:
          CF_ID_RAW: ${{ secrets.CLOUDFRONT_DIST_ID}} # ← ここ、あなたが設定した秘密名に合わせる
        run: |
          ID="${CF_ID_RAW//[$'\t\r\n ']/}"   # 余分な空白・改行を除去
          echo "::notice::CF_ID length = ${#ID}"  # 値はマスクされるが長さは見える
          test -n "$ID" || { echo "ERROR: CLOUDFRONT_DIST_IDis empty"; exit 1; }
          echo "CF_ID=$ID" >> "$GITHUB_ENV"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CF_ID" \
            --paths "/*"
        working-directory: .
