name: Deploy Frontend to S3

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug PWD & list
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la
        working-directory: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Guard - package.json exists
        run: test -f package.json || (echo "package.json not found in $(pwd)"; exit 1)
        working-directory: .

      - name: Install
        run: npm ci
        working-directory: .

      - name: Build (Next.js static export)
        run: |
          npm run build
          npm run export
          test -d out || (echo "out/ not found after export"; exit 1)
        working-directory: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-northeast-1' }}

      - name: Sync to S3
        run: aws s3 sync out s3://${{ secrets.FRONTEND_S3_BUCKET }} --delete
        working-directory: .

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
        working-directory: .
